### ISSUE TITLE
upbound_window value to 1.0

### ISSUE THREAD

**Issue by guatavita** [Synho/windows_optimization#1]
Hello, 

Great work. 

Was wondering if it was possible to have the same behavior with upbound_window= 1.0.

In that particular cases, the filter does not work with the sigmoid activation and is not correct with the relu activation.

Any plan or idea to correct that?

Thank you!

**Comment by Myeongchan-Kim** [comment]
Ah, I think that was caused by a smooth factor (=a very small epsilon value to set a widow width for sigmoid functions). Please set the smaller smooth factor such as 1/255.0

I will add to codes later. Thank you for noticing.

**Comment by Myeongchan-Kim** [comment]
Sorry for late updating. I added one commit for change smooth value. But I didn't test it yet, so please let me know if it doesn't work. 

see 6f608a28caced30f54650934d5ef9d44a318e577
